services:
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      CLUSTER_ID: "EmptNWtoR4GGWx-BH6nGLQ"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_AUTOCREATE_TOPICS_ENABLE: "false"
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-init:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-init
    depends_on:
      - kafka
    volumes:
      - ./kafka/create-topics.sh:/tmp/create-topics.sh:z
    command: ["bash", "/tmp/create-topics.sh"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  producer:
    image: crypto_producer:latest
    container_name: producer
    depends_on:
      - kafka-init
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  spark-processor:
    image: crypto_spark_processor:latest
    container_name: spark-processor
    depends_on:
      - producer
    volumes:
      - pyspark_checkpoints:/tmp/spark/checkpoint/vwap:Z
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  dashboard:
    image: crypto_dashboard:latest
    container_name: dashboard
    depends_on:
      - spark-processor
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: ["sh", "-c", "sleep 30 && streamlit run app.py"]

volumes:
  kafka_data:
  pyspark_checkpoints:
