version: '3.8'

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: 'q1W2e6F1t5H3u6i0J8R0weQ48Edaos'
      CLUSTER_ID: 'q1W2e6F1t5H3u6i0J8R0weQ48Edaos'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

    volumes:
      - kafka_data:/var/lib/kafka/data
    entrypoint:
      - sh
      - -c
      - |

        if [ ! -f "/var/lib/kafka/data/meta.properties" ]; then
          echo "Formatting KRaft storage with cluster ID $CLUSTER_ID..."
          /opt/kafka/bin/kafka-storage.sh format \
            --config /opt/kafka/config/server.properties \
            --cluster-id "$CLUSTER_ID"
            --standalone
        fi

        exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties

volumes:
  kafka_data:
